### ISSUE TITLE
icon_emoji not showing up?

### ISSUE THREAD

**Issue by nodesocket** [xoxco/node-slack#19]
I am using:

```
icon_emoji: 'heavy_exclamation_mark',
```

But the message has no icon:

![screen shot 2015-07-23 at 7 15 47 pm](https://cloud.githubusercontent.com/assets/523312/8866255/3cf87956-316f-11e5-90c9-67b5cb1f787b.png)

**Comment by jforaker** [comment]
should be
```
icon_emoji: ':heavy_exclamation_mark:',
```
